DPP = DPP or {}

DPP.DefaultConfig = {
    profiles = {
        active = "default",
        available = { "default" },
        allowImportExport = true,
        multiServerSync = false,
    },

    core = {
        masterEnable = true,
        globalQuickActions = true,
        smartHookRegistration = true,
        optimizedNetworking = true,
        asyncCleanupBatchSize = 100,
        notifyThrottleSeconds = 3,
    },

    general = {
        enabled = true,
        playerManagement = {
            playerList = true,
            playerSearch = true,
        },
        actionButtons = {
            ghostProps = true,
            freezeProps = true,
            removeProps = true,
            removeEntities = true,
            highlightEntities = true,
        },
        globalPropActions = {
            ghostEveryoneProps = true,
            freezeEveryoneProps = true,
            removeDisconnectedEntities = true,
            removeDisconnectTimerSeconds = 120,
            removeDisconnectedSpecificList = {},
            removeOutOfBoundsTimerSeconds = 60,
            outOfBoundsWhitelist = {},
            protectedFrozenEntities = {},
            blacklist = {},
        },
    },

    ghosting = {
        enabled = true,
        color = { r = 50, g = 150, b = 255, a = 120 },
        antiObscuringEntities = {},
        ghostOnPhysgun = true,
        useBlacklist = true,
        ghostableEntities = {
            ["prop_physics"] = true,
        },
        forceGhostUnfrozen = false,
        forceGhostUnfrozenWhitelist = {},
    },

    damage = {
        enabled = true,
        useBlacklist = true,
        blacklistedEntities = {},
        disableBlacklistedEntityDamage = true,
        disableVehicleDamage = true,
        disableWorldDamage = false,
        immortalEntities = {},
        bypassGroups = { "superadmin" },
        canDamageWorldEntities = {},
    },

    antiCollide = {
        enabled = true,
        notifyStaff = true,
        protectDarkRPEntities = true,
        darkRPEntityThreshold = 125,
        darkRPEntityExceptionList = {},
        protectSpawnedEntities = true,
        spawnedEntitiesThreshold = 75,
        spawnedEntitiesExceptionList = {},
        protectSpawnedProps = true,
        spawnedPropsThreshold = 45,
        spawnedPropsException = {},
        specificEntities = {},
    },

    spamProtection = {
        enabled = true,
        spawnThreshold = 66,
        spawnDelay = 1,
        punishmentMode = "cleanup",
        notifyStaff = true,
        protectProps = true,
        protectEntities = true,
        debounceWindow = 0.15,
    },

    spawnRestriction = {
        enabled = true,
        propSpawnPermissions = {},
        sentSpawnPermissions = {},
        swepSpawnPermissions = {},
        vehicleSpawnPermissions = {},
        npcSpawnPermissions = {},
        ragdollSpawnPermissions = {},
        effectSpawnPermissions = {},
        blockedSENTs = {},
        blockedClassesAsBlacklist = true,
        blockedModels = {},
        blockedModelsAsBlacklist = true,
        spawnVehicleBypassBlockedModels = true,
        bypassGroups = { "superadmin" },
        perMapLimits = {},
        perJobLimits = {},
        perRankMultipliers = {},
    },

    toolgun = {
        enabled = true,
        canTargetWorldEntities = false,
        canTargetPlayerOwnedEntities = false,
        restrictedTools = {},
        groupToolRestrictions = {},
        entityTargetability = {},
        bypassTargetabilityTools = {},
        bypassGroups = { "superadmin" },
        antiSpam = true,
    },

    physgun = {
        enabled = true,
        canTargetWorldEntities = false,
        canTargetPlayerOwnedEntities = false,
        disableReloadUnfreeze = true,
        pickupVehiclePermission = {},
        stopMotionOnDrop = false,
        blockMultiplePhysgunning = true,
        maxObstructThreshold = 3,
        maxObstructTriggerAction = "notify",
        blockedEntities = {},
        bypassGroups = { "superadmin" },
    },

    gravgun = {
        enabled = true,
        canTargetWorldEntities = false,
        canTargetPlayerOwnedEntities = false,
        disableGravityGunPunting = true,
        blockedEntities = {},
        bypassGroups = { "superadmin" },
    },

    canProperty = {
        enabled = true,
        canTargetWorldEntities = false,
        canTargetPlayerOwnedEntities = false,
        blockedProperties = {},
        blockedPropertiesAsBlacklist = true,
        blockedEntities = {},
        bypassGroups = { "superadmin" },
    },

    advDupe2 = {
        enabled = true,
        notifyStaff = true,
        preventRopeSpawning = true,
        preventScaling = true,
        preventNoGravity = true,
        preventTrails = true,
        preventUnreasonableValues = true,
        preventUnfreezeAll = true,
        blacklistedCollisionGroups = {},
        whitelistedConstraints = {},
        importValidation = true,
        dupeSandboxing = true,
    },

    miscs = {
        enabled = true,
        clearDecalsTimer = 120,
        preventBlackoutExploit = true,
        preventFadingDoorLag = true,
        disableMotionGlobally = false,
        disableMotionEntitiesList = {},
        freezeOnSpawn = false,
        preventFadingDoorAbuse = true,
        preventSpawnNearPlayerDistance = 10,
        forceOwnershipOnDarkRPEntities = true,
        maxObstructsOnPurchaseDarkRPEnts = 3,
        maxObstructFilterDarkRPEnts = 1,
    },

    ownership = {
        enabled = true,
        trustSystem = true,
        temporaryTrust = true,
        temporaryTrustDefaultMinutes = 30,
        teamBasedTrust = false,
        perPropTrustOverride = true,
        sharedOwnershipMode = false,
        transferOwnershipCommand = "dpp_transfer_ownership",
        autoTransferOnTeamChange = false,
        cleanupOnPermaban = true,
        cleanupOnSteamIDBan = true,
        ownershipLogs = true,
        lazyOwnershipAssignment = true,
        entityCacheEnabled = true,
    },

    logging = {
        enabled = true,
        fileLogging = true,
        consoleLogging = true,
        actionHistorySize = 500,
        violationHistorySize = 1000,
        liveMonitorEnabled = true,
        undoBlockLogEnabled = true,
    },

    antiCrash = {
        enabled = true,
        constraintCountLimiter = 1500,
        weldCountLimiter = 700,
        parentingLoopDetection = true,
        recursiveConstraintDetection = true,
        vehicleSpamCrashProtection = true,
        physicsExplosionDetection = true,
        massSpawnSpikeDetection = true,
        tickLagMonitorAutoFreeze = true,
        serverFPSAutoProtectionMode = true,
        autoProtectionFPSFloor = 22,
    },

    automation = {
        enabled = true,
        autoFreezeLargeContraptions = true,
        autoGhostLargeBuilds = false,
        autoCleanupAbandonedBases = true,
        buildInactivityTimerCleanupSeconds = 3600,
        buildAreaSizeLimiter = 12000,
    },

    permissions = {
        enabled = true,
        useULX = true,
        useCAMI = true,
        roleBasedConfig = true,
        perFeatureGroupOverride = {},
        featureOverridePriority = { "superadmin", "admin", "user" },
    },

    qol = {
        enabled = true,
        buildIndicator = true,
        noOwnershipHUDWarning = true,
        ghostPreviewTransparencySlider = true,
        buildModeToggle = true,
        personalCleanupCommand = true,
        autoFreezePerPlayerToggle = true,
        personalPropLimitIndicator = true,
        clientPropCounter = true,
    },
}

DPP.Config = DPP.Config or DPP:DeepCopy(DPP.DefaultConfig)
DPP:Merge(DPP.Config, DPP.DefaultConfig)
